### PR TITLE
Get state variables initial values from solver

### PR DESCRIPTION
**Pull request by RuomeiYan**
Get state variables' initial values from the solver solution.

Example translation:
Dash
```
conc state Puzzle {
    near: set Object
    far: set Object
    eatsRel: set Object -> set Object

    init {
        near = Object
        no far
        eatsRel = eats
    }
```
Python
```
        # state variable declarations
        SS.Puzzle_near = Object('near', 3, {"Chicken$0", "Farmer$0", "Fox$0", "Grain$0"})
        SS.Puzzle_far = Object('far', 3, {})
        SS.Puzzle_eatsRel = Relation('eatsRel', [Object, Object], {("Chicken$0", "Grain$0"), ("Fox$0", "Chicken$0")})

```

### CODE REVIEW

**Review by AidanCampbell738 — APPROVED** [review]

**Review by Chestshire — APPROVED** [review]
LGTM. Will need to refine the prompts for the users (or user experience) later.

**Comment by Simonliuwaterloo** [comment]
Unable to run given example in your branch:
```
> Task :org.alloytools.alloy.application:RapidDash.main()
Please specify the .dsh file path:
Parsing Model
=========== Parsing+Typechecking farmer.dsh =============
Exception in thread "main" java.lang.NullPointerException
	at edu.mit.csail.sdg.ast.Func.<init>(Func.java:183)
	at ca.uwaterloo.watform.parser.DashModule.addFunc(DashModule.java:2895)
	at ca.uwaterloo.watform.transform.CoreDashToAlloy.addSmallStepPredicateAST(CoreDashToAlloy.java:1366)
	at ca.uwaterloo.watform.transform.CoreDashToAlloy.createSmallStepAST(CoreDashToAlloy.java:1064)
	at ca.uwaterloo.watform.transform.CoreDashToAlloy.convertToAlloyAST(CoreDashToAlloy.java:58)
	at ca.uwaterloo.watform.dash4whole.RapidDash.main(RapidDash.java:69)

> Task :org.alloytools.alloy.application:RapidDash.main() FAILED

Execution failed for task ':org.alloytools.alloy.application:RapidDash.main()'.
> Process 'command '/usr/local/Cellar/openjdk@8/1.8.0+302/libexec/openjdk.jdk/Contents/Home/bin/java'' finished with non-zero exit value 1

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
```
Seems to be related to this line `            DashModule alloy = DashOptions.isElectrum ? new CoreDashToElectrum().convertToElectrumAST(coreDash, "", "") : new CoreDashToAlloy().convertToAlloyAST(coreDash, "", "");`

**Comment by Simonliuwaterloo** [comment]
> Unable to run given example in your branch:
> 
> ```
> > Task :org.alloytools.alloy.application:RapidDash.main()
> Please specify the .dsh file path:
> Parsing Model
> =========== Parsing+Typechecking farmer.dsh =============
> Exception in thread "main" java.lang.NullPointerException
> 	at edu.mit.csail.sdg.ast.Func.<init>(Func.java:183)
> 	at ca.uwaterloo.watform.parser.DashModule.addFunc(DashModule.java:2895)
> 	at ca.uwaterloo.watform.transform.CoreDashToAlloy.addSmallStepPredicateAST(CoreDashToAlloy.java:1366)
> 	at ca.uwaterloo.watform.transform.CoreDashToAlloy.createSmallStepAST(CoreDashToAlloy.java:1064)
> 	at ca.uwaterloo.watform.transform.CoreDashToAlloy.convertToAlloyAST(CoreDashToAlloy.java:58)
> 	at ca.uwaterloo.watform.dash4whole.RapidDash.main(RapidDash.java:69)
> 
> > Task :org.alloytools.alloy.application:RapidDash.main() FAILED
> 
> Execution failed for task ':org.alloytools.alloy.application:RapidDash.main()'.
> > Process 'command '/usr/local/Cellar/openjdk@8/1.8.0+302/libexec/openjdk.jdk/Contents/Home/bin/java'' finished with non-zero exit value 1
> 
> * Try:
> > Run with --stacktrace option to get the stack trace.
> > Run with --info or --debug option to get more log output.
> > Run with --scan to get full insights.
> ```
> 
> Seems to be related to this line ` DashModule alloy = DashOptions.isElectrum ? new CoreDashToElectrum().convertToElectrumAST(coreDash, "", "") : new CoreDashToAlloy().convertToAlloyAST(coreDash, "", "");`

The error stack:
```
<init>:183, Func (edu.mit.csail.sdg.ast)
addFunc:2895, DashModule (ca.uwaterloo.watform.parser)
addSmallStepPredicateAST:1366, CoreDashToAlloy (ca.uwaterloo.watform.transform)
createSmallStepAST:1064, CoreDashToAlloy (ca.uwaterloo.watform.transform)
convertToAlloyAST:58, CoreDashToAlloy (ca.uwaterloo.watform.transform)
main:69, RapidDash (ca.uwaterloo.watform.dash4whole)
```
The `expression` is null here:
image
My git status:
image
I changed the content of farmer.dsh to the example you provided above.

@RuomeiYan can you check if you can reproduce this?

**Comment by Chestshire** [comment]
> > Unable to run given example in your branch:
> > ```
> > > Task :org.alloytools.alloy.application:RapidDash.main()
> > Please specify the .dsh file path:
> > Parsing Model
> > =========== Parsing+Typechecking farmer.dsh =============
> > Exception in thread "main" java.lang.NullPointerException
> > 	at edu.mit.csail.sdg.ast.Func.<init>(Func.java:183)
> > 	at ca.uwaterloo.watform.parser.DashModule.addFunc(DashModule.java:2895)
> > 	at ca.uwaterloo.watform.transform.CoreDashToAlloy.addSmallStepPredicateAST(CoreDashToAlloy.java:1366)
> > 	at ca.uwaterloo.watform.transform.CoreDashToAlloy.createSmallStepAST(CoreDashToAlloy.java:1064)
> > 	at ca.uwaterloo.watform.transform.CoreDashToAlloy.convertToAlloyAST(CoreDashToAlloy.java:58)
> > 	at ca.uwaterloo.watform.dash4whole.RapidDash.main(RapidDash.java:69)
> > 
> > > Task :org.alloytools.alloy.application:RapidDash.main() FAILED
> > 
> > Execution failed for task ':org.alloytools.alloy.application:RapidDash.main()'.
> > > Process 'command '/usr/local/Cellar/openjdk@8/1.8.0+302/libexec/openjdk.jdk/Contents/Home/bin/java'' finished with non-zero exit value 1
> > 
> > * Try:
> > > Run with --stacktrace option to get the stack trace.
> > > Run with --info or --debug option to get more log output.
> > > Run with --scan to get full insights.
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Seems to be related to this line ` DashModule alloy = DashOptions.isElectrum ? new CoreDashToElectrum().convertToElectrumAST(coreDash, "", "") : new CoreDashToAlloy().convertToAlloyAST(coreDash, "", "");`

I tried this model and it's working. It fails if I delete the transition (getting the same error as above)
```
abstract sig Object {
    eats: set Object
}

one sig Farmer extends Object {}

conc state Puzzle {
    near: set Object
    far: set Object

    init {
        near = Object
        no far
    }

    trans near2far {
        when near in near
        do near' = near - near'.eats
    }
}
```

**Comment by Simonliuwaterloo** [comment]
> > > Unable to run given example in your branch:
> > > ```
> > > > Task :org.alloytools.alloy.application:RapidDash.main()
> > > Please specify the .dsh file path:
> > > Parsing Model
> > > =========== Parsing+Typechecking farmer.dsh =============
> > > Exception in thread "main" java.lang.NullPointerException
> > > 	at edu.mit.csail.sdg.ast.Func.<init>(Func.java:183)
> > > 	at ca.uwaterloo.watform.parser.DashModule.addFunc(DashModule.java:2895)
> > > 	at ca.uwaterloo.watform.transform.CoreDashToAlloy.addSmallStepPredicateAST(CoreDashToAlloy.java:1366)
> > > 	at ca.uwaterloo.watform.transform.CoreDashToAlloy.createSmallStepAST(CoreDashToAlloy.java:1064)
> > > 	at ca.uwaterloo.watform.transform.CoreDashToAlloy.convertToAlloyAST(CoreDashToAlloy.java:58)
> > > 	at ca.uwaterloo.watform.dash4whole.RapidDash.main(RapidDash.java:69)
> > > 
> > > > Task :org.alloytools.alloy.application:RapidDash.main() FAILED
> > > 
> > > Execution failed for task ':org.alloytools.alloy.application:RapidDash.main()'.
> > > > Process 'command '/usr/local/Cellar/openjdk@8/1.8.0+302/libexec/openjdk.jdk/Contents/Home/bin/java'' finished with non-zero exit value 1
> > > 
> > > * Try:
> > > > Run with --stacktrace option to get the stack trace.
> > > > Run with --info or --debug option to get more log output.
> > > > Run with --scan to get full insights.
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > Seems to be related to this line ` DashModule alloy = DashOptions.isElectrum ? new CoreDashToElectrum().convertToElectrumAST(coreDash, "", "") : new CoreDashToAlloy().convertToAlloyAST(coreDash, "", "");`
> 
> I tried this model and it's working. It fails if I delete the transition (getting the same error as above)
> 
> ```
> abstract sig Object {
>     eats: set Object
> }
> 
> one sig Farmer extends Object {}
> 
> conc state Puzzle {
>     near: set Object
>     far: set Object
> 
>     init {
>         near = Object
>         no far
>     }
> 
>     trans near2far {
>         when near in near
>         do near' = near - near'.eats
>     }
> }
> ```

I see, I was using the example in the overview of this pr:
```
conc state Puzzle {
    near: set Object
    far: set Object
    eatsRel: set Object -> set Object

    init {
        near = Object
        no far
        eatsRel = eats
    }
}
```

**Comment by Chestshire** [comment]
> 

I tried the one with `eatsRel: set Object -> set Object` and `eatsRel = eats` too. A preliminary guess is that problem would happen if we have no transitions.

**Review by Simonliuwaterloo — APPROVED** [review]

**Pull request merged**
